# Generated by Django 6.1.1 on 2026-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя в Telegram')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активен'), ('blocked', 'Заблокирован')], default='pending', max_length=16, verbose_name='Статус')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Суперадмин')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления о новых письмах')),
                ('send_attachments', models.BooleanField(default=True, verbose_name='Сразу присылать вложения')),
                ('signature', models.TextField(blank=True, verbose_name='Подпись в письмах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
                'ordering': ['-created_at'],
            },
        ),
    ]
