# Generated by Django 6.1.1 on 2026-10-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Начало дня'), ('close', 'Завершение дня')], max_length=8)),
                ('requested_time', models.TimeField(verbose_name='Указанное время')),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_logs', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Рабочий день: действие',
                'verbose_name_plural': 'Рабочий день: журнал',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkdayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=255, verbose_name='Логин Битрикс')),
                ('password_encrypted', models.TextField(blank=True, verbose_name='Пароль Битрикс (зашифрован)')),
                ('bitrix_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID в Битриксе')),
                ('remind_start', models.TimeField(blank=True, null=True, verbose_name='Напомнить начать день')),
                ('remind_end', models.TimeField(blank=True, null=True, verbose_name='Напомнить завершить день')),
                ('last_start_reminder', models.DateField(blank=True, null=True)),
                ('last_end_reminder', models.DateField(blank=True, null=True)),
                ('auth_failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя ошибка входа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workday', to='accounts.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рабочий день: профиль',
                'verbose_name_plural': 'Рабочий день: профили',
            },
        ),
    ]
