# Generated by Django 6.1.1 on 2026-09-28 07:27

import apps.mail.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password_encrypted', models.TextField(verbose_name='Пароль (зашифрован)')),
                ('imap_host', models.CharField(default=apps.mail.models._imap_host, max_length=255, verbose_name='IMAP хост')),
                ('imap_port', models.PositiveIntegerField(default=apps.mail.models._imap_port, verbose_name='IMAP порт')),
                ('smtp_host', models.CharField(default=apps.mail.models._smtp_host, max_length=255, verbose_name='SMTP хост')),
                ('smtp_port', models.PositiveIntegerField(default=apps.mail.models._smtp_port, verbose_name='SMTP порт')),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'Без шифрования')], default=apps.mail.models._smtp_security, max_length=16, verbose_name='SMTP шифрование')),
                ('sent_folder', models.CharField(blank=True, max_length=255, verbose_name='Папка «Отправленные»')),
                ('is_active', models.BooleanField(default=True, verbose_name='Синхронизация включена')),
                ('needs_reauth', models.BooleanField(default=False, verbose_name='Требуется повторный вход')),
                ('reauth_notified', models.BooleanField(default=False)),
                ('inbox_uidvalidity', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='UIDVALIDITY')),
                ('last_uid', models.PositiveBigIntegerField(default=0, verbose_name='Последний UID')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок подряд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключён')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to='accounts.telegramuser', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Почтовый ящик',
                'verbose_name_plural': 'Почтовые ящики',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('seen_count', models.PositiveIntegerField(default=0, verbose_name='Встречался в письмах')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Писали ему')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mail.mailaccount')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Входящее'), ('out', 'Исходящее')], default='in', max_length=3)),
                ('folder', models.CharField(default='INBOX', max_length=255, verbose_name='Папка')),
                ('uid', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uidvalidity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('message_id', models.CharField(db_index=True, max_length=512, verbose_name='Message-ID')),
                ('in_reply_to', models.CharField(blank=True, max_length=512, verbose_name='In-Reply-To')),
                ('references', models.TextField(blank=True, verbose_name='References')),
                ('kind', models.CharField(choices=[('new', 'Новое'), ('reply', 'Ответ'), ('forward', 'Пересланное'), ('auto', 'Автоответ'), ('calendar', 'Приглашение')], default='new', max_length=16, verbose_name='Тип')),
                ('importance', models.CharField(choices=[('low', 'Низкая'), ('normal', 'Обычная'), ('high', 'Высокая')], default='normal', max_length=8, verbose_name='Важность')),
                ('from_name', models.CharField(blank=True, max_length=255, verbose_name='От (имя)')),
                ('from_email', models.CharField(blank=True, db_index=True, max_length=320, verbose_name='От (e-mail)')),
                ('reply_to', models.CharField(blank=True, max_length=512, verbose_name='Reply-To')),
                ('subject', models.TextField(blank=True, verbose_name='Тема')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата')),
                ('body_text', models.TextField(blank=True, verbose_name='Текст')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML')),
                ('body_new_text', models.TextField(blank=True, verbose_name='Текст без цитаты')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер')),
                ('raw', models.FileField(blank=True, null=True, upload_to=apps.mail.models.raw_upload_to, verbose_name='Оригинал (.eml)')),
                ('notify', models.BooleanField(default=True, verbose_name='Уведомлять')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Уведомление отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailaccount')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.mail.models.attachment_upload_to)),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_id', models.CharField(blank=True, max_length=255, verbose_name='Content-ID')),
                ('is_inline', models.BooleanField(default=False, verbose_name='Встроено в текст')),
                ('tg_file_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id (кэш)')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mailmessage')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='MailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Тема (нормализованная)')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mail.mailaccount')),
            ],
            options={
                'verbose_name': 'Цепочка',
                'verbose_name_plural': 'Цепочки',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mail.mailthread'),
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('to', 'Кому'), ('cc', 'Копия'), ('bcc', 'Скрытая копия')], max_length=3)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=320)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mail.mailmessage')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('new', 'Новое'), ('reply', 'Ответ'), ('reply_all', 'Ответ всем'), ('forward', 'Пересылка')], default='new', max_length=16)),
                ('to', models.JSONField(default=list, verbose_name='Кому')),
                ('cc', models.JSONField(blank=True, default=list, verbose_name='Копия')),
                ('bcc', models.JSONField(blank=True, default=list, verbose_name='Скрытая копия')),
                ('subject', models.TextField(blank=True, verbose_name='Тема')),
                ('body_text', models.TextField(blank=True, verbose_name='Текст')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('smtp_message_id', models.CharField(blank=True, max_length=512)),
                ('result_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='mail.mailaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='accounts.telegramuser')),
                ('forward_attachments', models.ManyToManyField(blank=True, related_name='+', to='mail.mailattachment', verbose_name='Вложения исходного письма')),
                ('sent_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.mailmessage')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.mailmessage', verbose_name='Исходное письмо')),
            ],
            options={
                'verbose_name': 'Исходящее письмо',
                'verbose_name_plural': 'Исходящие письма',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.mail.models.outgoing_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.outgoingmessage')),
            ],
            options={
                'verbose_name': 'Файл исходящего письма',
                'verbose_name_plural': 'Файлы исходящих писем',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('tg_message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mail.mailmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.telegramuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mailaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'email'), name='uniq_owner_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', '-sent_count', '-seen_count'], name='mail_contac_account_be99c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('account', 'email'), name='uniq_contact_email'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', 'direction', '-date'], name='mail_mailme_account_3870b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['notified_at', 'notify'], name='mail_mailme_notifie_e69b84_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('uid__isnull', False)), fields=('account', 'folder', 'uidvalidity', 'uid'), name='uniq_message_uid'),
        ),
        migrations.AddIndex(
            model_name='telegramnotification',
            index=models.Index(fields=['chat_id', 'tg_message_id'], name='mail_telegr_chat_id_3b85c6_idx'),
        ),
    ]
