# Generated by Django 6.1.1 on 2026-09-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailaccount',
            name='reauth_notified',
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='reauth_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание о пароле отправлено'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='sent_last_uid',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Последний UID «Отправленных»'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='sent_uidvalidity',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='UIDVALIDITY «Отправленных»'),
        ),
    ]
