# Generated by Django 6.1.1 on 2026-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_sent_folder_reauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='read_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Статус прочтения изменён в боте'),
        ),
    ]
