# Generated by Django 6.1.1 on 2026-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_read_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='directory_failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Адресная книга: последний отказ входа'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='directory_login',
            field=models.CharField(blank=True, help_text='Например BSB\\ivanov. Пусто — подберётся автоматически', max_length=255, verbose_name='Логин для адресной книги Exchange'),
        ),
    ]
